// app/resources/js/components/other/Subscription.vue
<template>
    <div class="container py-3">
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <p class="alert alert-secondary">
                            Sign up with your email address to receive the website updates.
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                <form @submit.prevent="$refs.reCaptcha.verify">
                                    <div class="form-group">
                                        <label for="email">Email
                                            <small>Required</small>
                                        </label>
                                        <input type="email"
                                               required
                                               id="email"
                                               class="form-control"
                                               v-model.trim="email">
                                    </div>
                                    <div class="form-group">
                                        <re-captcha ref="reCaptcha" @verified="subscribe"></re-captcha>
                                    </div>
                                    <button :disabled="loading" type="submit" class="btn btn-secondary">Send</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    import ReCaptcha from "../utils/ReCaptcha";
    import {GoToMixin, MetaMixin} from "../../mixins";

    export default {
        components: {
            ReCaptcha,
        },
        mixins: [
            GoToMixin,
            MetaMixin,
        ],
        data: function () {
            return {
                loading: false,
                email: "",
            };
        },
        computed: {
            pageTitle: function () {
                return "Subscription";
            },
        },
        methods: {
            subscribe: async function (reCaptchaResponse) {
                this.loading = true;
                try {
                    await this.$dc.get("api").createSubscription({
                        email: this.email,
                        g_recaptcha_response: reCaptchaResponse,
                    });
                    this.$dc.get("notification").success("You have been successfully subscribed to the website updates.");
                    this.goToHomePage();
                } finally {
                    this.loading = false;
                }
            },
        },
    }
</script>

// frontend/src/app/components/subscription/subscription.component.ts
import {Component, Inject} from '@angular/core';
import {
    ApiService,
    TitleService,
    LockProcessServiceProvider,
    LockProcessService,
    NavigatorServiceProvider,
    NavigatorService,
} from '../../../shared/services';
import {NoticesService} from '../../../common/notices';
import {SubscriptionForm} from './subscription-form';

@Component({
    selector: 'subscription',
    templateUrl: 'subscription.component.html',
})
export class SubscriptionComponent {
    private form:SubscriptionForm;
    private navigator:NavigatorService;
    private lockProcess:LockProcessService;

    constructor(@Inject(ApiService) private api:ApiService,
                @Inject(TitleService) private title:TitleService,
                @Inject(NoticesService) private notices:NoticesService,
                @Inject(NavigatorServiceProvider) navigatorProvider:NavigatorServiceProvider,
                @Inject(LockProcessServiceProvider) lockProcessServiceProvider:LockProcessServiceProvider) {
        this.navigator = navigatorProvider.getInstance();
        this.lockProcess = lockProcessServiceProvider.getInstance();
    }

    ngOnInit() {
        this.title.setTitle('Subscription');
        this.form = new SubscriptionForm;
    }

    subscribe = () => {
        return this.lockProcess
            .process(() => this.api.post('/subscriptions', this.form).toPromise())
            .then((data:any) => {
                this.notices.success('You have successfully subscribed to the website updates.');
                this.navigator.navigate(['/']);
                return data;
            });
    };

    isLoading = ():boolean => {
        return this.lockProcess.isProcessing();
    };
}

<div class="ibox float-e-margins">
    <div class="ibox-content">
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-success">
                    {{ 'Sign up with your email address to receive the website updates.' }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{ 'Email' }}</label>
                        <div class="col-sm-10">
                            <input [(ngModel)]="form.email"
                                   (keyup.enter)="subscribe()"
                                   type="email"
                                   class="form-control"
                                   name="email"
                                   placeholder="{{ 'Your Email Address' }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button (click)="subscribe()" [disabled]="isLoading()" class="btn btn-primary">{{ 'Subscribe' }}</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
