// frontend/src/app/components/unsubscription/unsubscription.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {NoticesService} from '../../../lib';
import {
    ApiService,
    TitleService,
    ProcessLockerServiceProvider,
    ProcessLockerService,
    NavigatorServiceProvider,
    NavigatorService,
} from '../../../shared';

@Component({
    selector: 'unsubscription',
    templateUrl: 'unsubscription.component.html',
})
export class UnsubscriptionComponent implements OnInit {
    protected token:string = null;
    protected navigator:NavigatorService;
    protected processLocker:ProcessLockerService;

    constructor(protected route:ActivatedRoute,
                protected api:ApiService,
                protected title:TitleService,
                protected notices:NoticesService,
                navigatorProvider:NavigatorServiceProvider,
                processLockerServiceProvider:ProcessLockerServiceProvider) {
        this.navigator = navigatorProvider.getInstance();
        this.processLocker = processLockerServiceProvider.getInstance();
    }

    ngOnInit():void {
        this.title.setPageNameSegment('Unsubscription');
        this.initParamsSubscribers();
    }

    protected initParamsSubscribers = ():void => {
        this.route.params
            .map((params:any) => params['token'])
            .subscribe((token:string) => this.token = String(token));
    };

    unsubscribe():Promise<any> {
        return this.processLocker
            .lock(() => this.api.delete(`/subscriptions/${this.token}`))
            .then((data:any) => this.onUnsubscribeSuccess(data))
            .catch((error:any) => this.onUnsubscribeError(error));
    }

    onUnsubscribeSuccess(data:any):any {
        this.notices.success('You have been successfully unsubscribed from the website updates.');
        this.navigator.navigate(['/']);
        return data;
    }

    onUnsubscribeError(error:any):any {
        this.navigator.navigate(['/']);
        throw error;
    }

    navigateToHomePage():void {
        this.navigator.navigate(['/']);
    }

    isProcessing():boolean {
        return this.processLocker.isLocked();
    }
}

<div class="ibox float-e-margins">
    <div class="ibox-content">
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-success">
                    {{ 'Would you like to unsubscribe from receiving the website updates?' }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <button (click)="unsubscribe()" [disabled]="isProcessing()" class="btn btn-danger">{{ 'Yes' }}</button>
                <button (click)="navigateToHomePage()" [disabled]="isProcessing()" class="btn btn-primary">{{ 'No' }}
                </button>
            </div>
        </div>
    </div>
</div>

// app/resources/js/components/subscriptions/Unsubscription.vue
<template>
    <div class="container py-3">
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <p class="alert alert-secondary">
                            Would you like to unsubscribe from receiving the website updates?
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <button type="button" class="btn btn-danger" @click="unsubscribe" :disabled="loading">
                            Yes
                        </button>
                        <button type="button" class="btn btn-secondary" @click="goToHomePage" :disabled="loading">
                            No
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    import {GoToMixin, MetaMixin} from "../../mixins";

    export default {
        mixins: [
            GoToMixin,
            MetaMixin,
        ],
        data: function () {
            return {
                loading: false,
            };
        },
        computed: {
            pageTitle: function () {
                return "Unsubscription";
            },
        },
        methods: {
            unsubscribe: async function () {
                this.loading = true;
                try {
                    await this.$services.getApi().deleteSubscription(this.$route.params.token);
                    this.$services.getAlert().success("You have been successfully unsubscribed from the website updates.");
                } catch (error) {
                    // The error is handled by the API service.
                    // No additional actions needed.
                } finally {
                    this.loading = false;
                    this.goToHomePage();
                }
            },
        },
    }
</script>
